#!/bin/bash
# 3CX BackupWiz — Sync Service Installer
# Run as root on the 3CX server: bash install.sh

set -e

INSTALL_DIR="/opt/3cx-sync/3cx-backup-sync"
SERVICE_DIR="$INSTALL_DIR/sync-service"
ENV_FILE="$SERVICE_DIR/.env"
PM2_NAME="3cx-sync"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
prompt() { echo -e "\n${YELLOW}>>> $1${NC}"; }

echo ""
echo "=============================================="
echo "  3CX BackupWiz — Sync Service Installer"
echo "=============================================="
echo ""

# --- Prerequisite checks ---

if [ "$(id -u)" -ne 0 ]; then
  error "This script must be run as root."
  exit 1
fi

info "Checking prerequisites..."

# Node.js
if ! command -v node &>/dev/null; then
  info "Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
else
  info "Node.js $(node -v) found"
fi

# npm
if ! command -v npm &>/dev/null; then
  error "npm not found. Install Node.js first."
  exit 1
fi

# PM2
if ! command -v pm2 &>/dev/null; then
  info "Installing PM2..."
  npm install -g pm2
else
  info "PM2 $(pm2 -v) found"
fi

# git
if ! command -v git &>/dev/null; then
  info "Installing git..."
  apt-get install -y git
fi

# --- Clone or update repo ---

echo ""
if [ -d "$INSTALL_DIR" ]; then
  info "Repo already exists at $INSTALL_DIR — pulling latest..."
  cd "$INSTALL_DIR"
  git pull
else
  info "Cloning repo to $INSTALL_DIR..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone https://github.com/your-org/3cx-backup-sync.git "$INSTALL_DIR"
fi

# --- Collect environment variables ---

echo ""
echo "=============================================="
echo "  Configuration"
echo "=============================================="
echo ""
echo "Press ENTER to accept the default shown in [brackets]."
echo ""

# Supabase
prompt "Supabase project URL (e.g. https://xxxx.supabase.co):"
read -r SUPABASE_URL
if [ -z "$SUPABASE_URL" ]; then
  error "SUPABASE_URL is required."
  exit 1
fi

prompt "Supabase service role key:"
read -r SUPABASE_SERVICE_ROLE_KEY
if [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
  error "SUPABASE_SERVICE_ROLE_KEY is required."
  exit 1
fi

prompt "Supabase database URL (postgresql://postgres.xxx:password@aws-0-us-west-2.pooler.supabase.com:5432/postgres):"
read -r DATABASE_URL
if [ -z "$DATABASE_URL" ]; then
  error "DATABASE_URL is required."
  exit 1
fi

# DigitalOcean Spaces
echo ""
echo "--- DigitalOcean Spaces (required for recordings + media backup) ---"

prompt "DO Spaces access key (DO_SPACES_KEY):"
read -r DO_SPACES_KEY

prompt "DO Spaces secret key (DO_SPACES_SECRET):"
read -r DO_SPACES_SECRET

prompt "DO Spaces bucket name [3cxbackupwiz]:"
read -r DO_SPACES_BUCKET
DO_SPACES_BUCKET="${DO_SPACES_BUCKET:-3cxbackupwiz}"

prompt "DO Spaces endpoint [nyc3.digitaloceanspaces.com]:"
read -r DO_SPACES_ENDPOINT
DO_SPACES_ENDPOINT="${DO_SPACES_ENDPOINT:-nyc3.digitaloceanspaces.com}"

prompt "DO Spaces region [nyc3]:"
read -r DO_SPACES_REGION
DO_SPACES_REGION="${DO_SPACES_REGION:-nyc3}"

# 3CX local DB
echo ""
echo "--- 3CX Local PostgreSQL (on this server) ---"

prompt "3CX DB host [127.0.0.1]:"
read -r THREECX_DB_HOST
THREECX_DB_HOST="${THREECX_DB_HOST:-127.0.0.1}"

prompt "3CX DB port [5432]:"
read -r THREECX_DB_PORT
THREECX_DB_PORT="${THREECX_DB_PORT:-5432}"

prompt "3CX DB name [database_single]:"
read -r THREECX_DB_NAME
THREECX_DB_NAME="${THREECX_DB_NAME:-database_single}"

prompt "3CX DB user [phonesystem]:"
read -r THREECX_DB_USER
THREECX_DB_USER="${THREECX_DB_USER:-phonesystem}"

prompt "3CX DB password:"
read -r THREECX_DB_PASSWORD
if [ -z "$THREECX_DB_PASSWORD" ]; then
  warn "No DB password provided — OK if using peer auth"
fi

# Log level
prompt "Log level [info]:"
read -r LOG_LEVEL
LOG_LEVEL="${LOG_LEVEL:-info}"

# --- Write .env ---

info "Writing $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# 3CX BackupWiz Sync Service — generated by install.sh

# Supabase
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
DATABASE_URL=$DATABASE_URL

# DigitalOcean Spaces (recordings + media backup)
DO_SPACES_KEY=$DO_SPACES_KEY
DO_SPACES_SECRET=$DO_SPACES_SECRET
DO_SPACES_BUCKET=$DO_SPACES_BUCKET
DO_SPACES_ENDPOINT=$DO_SPACES_ENDPOINT
DO_SPACES_REGION=$DO_SPACES_REGION

# 3CX Local PostgreSQL
THREECX_DB_HOST=$THREECX_DB_HOST
THREECX_DB_PORT=$THREECX_DB_PORT
THREECX_DB_NAME=$THREECX_DB_NAME
THREECX_DB_USER=$THREECX_DB_USER
THREECX_DB_PASSWORD=$THREECX_DB_PASSWORD

# Sync intervals (seconds / minutes as noted)
SYNC_INTERVAL_CHAT=30
SYNC_INTERVAL_CDR=10
SYNC_INTERVAL_MEDIA=10
SYNC_INTERVAL_RECORDINGS=30

# Logging
LOG_LEVEL=$LOG_LEVEL
NODE_OPTIONS=--dns-result-order=ipv4first
EOF

info ".env written."

# --- Build ---

echo ""
info "Installing npm dependencies..."
cd "$SERVICE_DIR"
npm install

info "Building TypeScript..."
npm run build

# --- PostgreSQL trigger ---

echo ""
info "Installing 3CX LISTEN/NOTIFY trigger..."
TRIGGER_SQL="$INSTALL_DIR/scripts/3cx-realtime-trigger.sql"
if [ -f "$TRIGGER_SQL" ]; then
  PGPASSWORD="$THREECX_DB_PASSWORD" psql -h "$THREECX_DB_HOST" -p "$THREECX_DB_PORT" \
    -U "$THREECX_DB_USER" "$THREECX_DB_NAME" -f "$TRIGGER_SQL" && \
    info "Trigger installed." || warn "Trigger install failed — you may need to apply it manually."
else
  warn "Trigger SQL not found at $TRIGGER_SQL — skipping"
fi

# --- PM2 setup ---

echo ""
if pm2 list | grep -q "$PM2_NAME"; then
  info "Restarting existing PM2 process $PM2_NAME..."
  pm2 restart "$PM2_NAME" --update-env
else
  info "Starting $PM2_NAME with PM2..."
  cd "$SERVICE_DIR"
  pm2 start dist/index.js --name "$PM2_NAME" --time
fi

pm2 save

# Enable PM2 to survive reboots (only if not already set up)
if ! systemctl is-enabled pm2-root &>/dev/null 2>&1; then
  pm2 startup systemd -u root --hp /root | tail -1 | bash || true
  pm2 save
fi

echo ""
echo "=============================================="
echo "  Installation Complete!"
echo "=============================================="
echo ""
echo "  Service:   $PM2_NAME (PM2)"
echo "  Logs:      pm2 logs $PM2_NAME"
echo "  Status:    pm2 list"
echo "  Restart:   pm2 restart $PM2_NAME --update-env"
echo ""
if [ -z "$DO_SPACES_KEY" ] || [ -z "$DO_SPACES_SECRET" ]; then
  warn "DO Spaces was NOT configured — recordings and media backup are disabled."
  warn "Add DO_SPACES_KEY/SECRET to $ENV_FILE and run: pm2 restart $PM2_NAME --update-env"
fi
echo ""
